### ISSUE TITLE
Database SCHEMA

### ISSUE THREAD

**Issue by paulo-amaral** [CSProDevelopment/docker-csweb#1]
when starting csweb via docker, I was redirected to setup.
I accessed the mysql database via phpmyadmin and deleted the initial tables created; then I launched the installation again and was successful.
Please update mysql schema to version 7.7

:)

**Comment by aaronwhitesell** [comment]
Hi Paulo, I've updated the project to CSWeb 7.7.0. Thanks for opening an issue and let me know if you have any issues using the updated project.
