### ISSUE TITLE
release config error on file path

### ISSUE THREAD

**Issue by billyws** [CSProDevelopment/docker-csweb#3]
After running `docker-compose up`, it gave these to errors

1.  cannot create /var/www/html/src/api/app/config.php: Directory nonexistent
2. cannot create /var/www/html/src/ui/src/config.php: Directory nonexistent

To resolve this, I have add a line in the dockerfile, below _download and unzip csweb source_ to create these directories

### create directories for config files
`RUN mkdir -p /var/www/html/src/api/app /var/www/html/src/ui/src`

Anyone encountered the same issue, please share.

Cheers

**Comment by billyws** [comment]
I have written a blog post on this - https://medium.com/@somersbilly/implementing-csweb-on-docker-release-config-5757164373d3

**Comment by jhandley** [comment]
CSWeb changed the location of the config files since this code was written. More details on the real fix that is required is in the comments for this PR https://github.com/CSProDevelopment/docker-csweb/pull/2.

I'm not involved in CSPro work anymore so I haven't gotten around to updating this.

**Comment by aaronwhitesell** [comment]
Hi Billy, I've updated the project to CSWeb 7.7.0. Thanks for opening an issue and let me know if you have any issues using the updated project.
